# Generated by Django 5.1.1 on 2026-01-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, max_length=80, verbose_name='Описание сообщества'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Название сообщества'),
        ),
    ]
