# Generated by Django 5.1.1 on 2026-01-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_group_description_alter_group_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание сообщества'),
        ),
    ]
